version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: postgres  # Должно совпадать с Django
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_api
    restart: always
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://admin:admin@postgres:5432/postgres
    command: >
      bash -c "sleep 5 &&
               cd api &&
               python manage.py migrate &&
               python createsuperuser.py &&
               python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - shared_media:/app/api/uploads

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    restart: always
    depends_on:
      - django
    environment:
      - PYTHONPATH=/app
    command: >
      bash -c "sleep 3 && export PYTHONPATH=/app && python server/bot.py"
    volumes:
      - shared_media:/app/api/uploads

volumes:
  postgres_data:
  shared_media:

