# Generated by Django 5.1.6 on 2025-03-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('full_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Ожидание', 'Ожидание'), ('Оплачен', 'Оплачен')], default='Ожидание', max_length=20)),
            ],
        ),
    ]
